external_components:
  - source:
      type: local
      path: components

uart:
  - id: tf03k_uart
    rx_pin: ${uart_gpio}
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE
    rx_buffer_size: 256

tf03k_shunt:
  id: shunt${shunt_id}
  uart_id: tf03k_uart
  publish_interval: ${refresh_interval}
  online_timeout: 5s
  online:
    name: "${shunt_name} Online"
  state_of_charge:
    name: "${shunt_name} State of charge"
  voltage:
    name: "${shunt_name} Voltage"
  capacity:
    name: "${shunt_name} Battery capacity"
  current:
    name: "${shunt_name} Current"
  remaining_time:
    name: "${shunt_name} Remaining time"
    filters:
      - throttle: 60s
  power:
    name: "${shunt_name} Power"
    filters:
      - throttle: ${refresh_interval}
  charging_power:
    id: shunt${shunt_id}_charging_power_raw
    internal: true
  discharging_power:
    id: shunt${shunt_id}_discharging_power_raw
    internal: true

sensor:
  - platform: total_daily_energy
    name: "${shunt_name} Daily charged energy"
    id: shunt${shunt_id}_daily_charged_energy
    power_id: shunt${shunt_id}_charging_power_raw
    method: trapezoid
    state_class: "total_increasing"
    device_class: "energy"
    unit_of_measurement: kWh
    restore: ${restore_counters}
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
      - throttle: ${refresh_interval}
  - platform: total_daily_energy
    name: "${shunt_name} Daily discharged energy"
    id: shunt${shunt_id}_daily_discharged_energy
    power_id: shunt${shunt_id}_discharging_power_raw
    method: trapezoid
    state_class: "total_increasing"
    device_class: "energy"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    restore: ${restore_counters}
    filters:
      - multiply: 0.001
      - throttle: ${refresh_interval}
